import type { Metadata } from "next";
import "./globals.css";
import AuthContextProvider from "@/lib/context/AuthContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cupcake">
      <body className="min-h-screen">
        <AuthContextProvider>{children}</AuthContextProvider>
      </body>
    </html>
  );
}
